function(x) {
  xMatch <- function(p, x)    grepl(pattern=p, x=x, ignore.case = T)
  
  if(xMatch("Austin ISD", x)) return("AISD")
  if(xMatch("Austin", x) & xMatch("City", x)) return("CoA")
  if(xMatch("Dell$", x)) return("Dell")
  
  if(xMatch("IBM", x)) return("IBM")
  if(xMatch("Seton", x)) return("Seton")
  if(xMatch("StDavids", x)) return("StDvd")
  if(xMatch("State", x) & xMatch("Texas", x) & !xMatch("Univ", x)) return("SoTX")
  if(xMatch("UTexas", x) & !xMatch("Student", x)) return("UTexas")
  if(grepl("UT.", x) & !xMatch("Student", x)) return("UTexas")
  if(xMatch("Accenture", x)) return("Accn")
  if(xMatch("Apple", x)) return("Appl")
  if(xMatch("Applied Materials", x)) return("AppM")
  if(xMatch("AT&T", x)) return("ATnT")
  if(xMatch("^ACC$", x) | xMatch("Austin", x) &
     xMatch("College", x) & xMatch("Community", x)) return("AAC")
  if(xMatch("Flextronics", x)) return("Flxtr")
  if(xMatch("Freescale", x)) return("Frscl")
  if(xMatch("HISD", x) | xMatch("Hays", x) & xMatch("ISD", x)) return("HISD")
  if(xMatch("Keller Williams", x)) return("KllrW")
  if(xMatch("LISD", x) | xMatch("Leander", x) & xMatch("ISD", x)) return("LISD")
  if(xMatch("National Instruments", x)) return("NtnlI")
  if(xMatch("PISD", x) | xMatch("Pflugerville", x) & xMatch("ISD", x)) return("PfISD")
  if(xMatch("RRISD", x) | xMatch("Round Rock", x) & xMatch("ISD", x)) return("RRISD")
  if(xMatch("Samsung", x)) return("Smsng")
  if(xMatch("State", x) & xMatch("Texas", x) & xMatch("Univ", x)) return("TxsSt")
  if(xMatch("Travis", x) | xMatch("County", x)) return("TrvsC")
  if(xMatch("^IRS", x) | xMatch("Revenue Service", x)) return("IRS")
  if(xMatch("Whole Foods", x)) return("WhlFd")
  if(xMatch("3M", x)) return("MMM")
  if(xMatch("^AMD$", x) | xMatch("Advanced Micro", x)) return("AMD")
  if(xMatch("Austin Energy", x)) return("AstnE")
  if(xMatch("Austin Regional Clinic", x)) return("AstRC")
  if(xMatch("Baylor Scott", x)) return("BSnW")
  if(xMatch("Charles Schwab", x)) return("ChrlS")
  if(xMatch("^GM$", x) | xMatch("General Motors", x)) return("GM")
  if(xMatch("Goodwill", x)) return("Gdwll")
  if(xMatch("^HP$", x) | xMatch("Hewlett", x)) return("HP")
  if(xMatch("HomeAway", x)) return("HmAwy")
  if(xMatch("Hospira", x)) return("Hospr")
  if(xMatch("Intel", x)) return("Intel")
  if(xMatch("Colorado River Authority", x) | xMatch("LCRA", x)) return("LCRA")
  if(xMatch("Oracle", x)) return("Oracl")
  if(xMatch("Progressive", x)) return("Prgrs")
  if(xMatch("Sears", x)) return("Sears")
  if(xMatch("State Farm", x)) return("StFrm")
  if(xMatch("Time Warner", x) | xMatch("TWC", x)) return("TWC")
  if(xMatch("URS", x)) return("URS")
  if(xMatch("Veterans Affairs", x) | xMatch("^VA", x)) return("VA")
  if(xMatch("Wells Fargo", x)) return("WllsF")
  if(xMatch("Activision", x)) return("ActvB")
  if(xMatch("American Campus", x)) return("AmrCC")
  if(xMatch("American Cancer ", x)) return("ACS")
  if(xMatch("BAE", x)) return("BAESy")
  if(xMatch("Bank", x) & xMatch("America", x)) return("BnkoA")
  if(xMatch("Bazaarvoice", x)) return("Bzrvc")
  if(xMatch("CFAN", x)) return("CFAN")
  if(xMatch("Cirrus Logic", x)) return("CrrsL")
  if(xMatch("Cisco", x)) return("Cisco")
  if(xMatch("Clinical Pathology Lab", x)) return("ClnPL")
  if(xMatch("Concentrix", x)) return("Cncnt")
  if(xMatch("eBay", x)) return("eBay")
  if(xMatch("Electric.+Council", x)) return("ERCoT")
  if(xMatch("Electronic Arts", x)) return("ElctA")
  if(xMatch("Emerson", x)) return("EmrPM")
  if(xMatch("Facebook", x)) return("Facbk")
  if(xMatch("Farmers Insurance", x)) return("FrmIG")
  if(xMatch("Google", x)) return("Googl")
  if(xMatch("^Grande$", x) | xMatch("Grande Communications", x)) return("GrndC")
  if(xMatch("Harte.Hank", x)) return("HrtH")
  if(xMatch("^HEB", x) | xMatch("H-E-B", x)) return("HEB")
  if(xMatch("Home Depot", x)) return("HmDpt")
  if(xMatch("Image Microsystems", x)) return("ImgMc")
  if(xMatch("JP", x) & xMatch("Morgan", x) | xMatch("Chase", x)) return("JMCnC")
  if(xMatch("Liquidation", x)) return("ThLqC")
  if(xMatch("Maximus", x)) return("Maxms")
  if(xMatch("Pearson", x)) return("Persn")
  if(xMatch("Pharma.+Dev", x)) return("PhrPD")
  if(xMatch("Q2", x)) return("Q2")
  if(xMatch("Rackspace", x)) return("Rcksp")
  if(xMatch("Silicon Lab", x)) return("SlcnL")
  if(xMatch("SolarWinds", x)) return("SlrWn")
  if(xMatch("Spansion", x)) return("Spnsn")
  if(xMatch("Edwards", x)) return("StEdw")
  if(xMatch("Visa", x)) return("Visa")
  if(xMatch("VMWare", x)) return("VMWar")
  if(xMatch("Volusion", x)) return("Volsn")
  if(xMatch("Wayne", x)) return("WynFS")
  if(xMatch("Xerox", x)) return("Xerox")
  if(xMatch("Yodle", x)) return("Yodle")
  if(xMatch("Federal", x) | xMatch("Veterans Affairs", x) | 
     xMatch("Revenue Service", x) | xMatch("^IRS", x) | 
     xMatch("^US ", x) | xMatch("gov", x) & 
     !xMatch("Credit", x)) return("Feds")
  return(NA)
}






 